import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.css";
import { StationProvider }  from '@/context/IdStationURL';
import DataUserProvider from '@/context/dataUser';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DataUserProvider>
      <StationProvider>
        {children}
     </StationProvider>
      </DataUserProvider>

        </body>
      <title>SST</title>
    
    </html>
  )
}
