import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import styles from "/app/page.module.css";
import IdCuveProvider from "@/context/idCuveURL";
import { IdVoletProvider } from "@/context/idVoletURL";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: 'Create Next App',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
        <div className={styles.main}>
            <div className={styles.navbar}>
              <Navbar />
            </div>
          <div className={styles.body}>
            <div className={styles.SideBar}>
              <Sidebar />
            </div>

            <div className={styles.Content}>
            <IdCuveProvider>
            <IdVoletProvider>

              {children}
            </IdVoletProvider>

            </IdCuveProvider>

              </div>
          </div>
            {/* <div className={styles.footer} ></div> */}
        </div>
     
  );
}
